# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-24 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('approved', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ('approved', 'name'),
            },
        ),
    ]
