# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ('approved', 'name'), 'verbose_name': 'school', 'verbose_name_plural': 'schools'},
        ),
    ]
