# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 17:48
from __future__ import unicode_literals

import contest.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import prologin.models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_native_jsonfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestantcorrection',
            options={'get_latest_by': 'date_created', 'ordering': ('-date_created',)},
        ),
        migrations.AlterField(
            model_name='contestant',
            name='assignation_final',
            field=prologin.models.EnumField(contest.models.Assignation, choices=[(0, 'Not assigned'), (1, 'Ruled out'), (2, 'Assigned')], default=0, verbose_name='Final assignation status'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='assignation_semifinal',
            field=prologin.models.EnumField(contest.models.Assignation, choices=[(0, 'Not assigned'), (1, 'Ruled out'), (2, 'Assigned')], default=0, verbose_name='Regional event assignation status'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='assignation_semifinal_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_contestants', to='contest.Event', verbose_name='Regional event assigned event'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='assignation_semifinal_wishes',
            field=models.ManyToManyField(blank=True, related_name='applicants', through='contest.EventWish', to='contest.Event', verbose_name='Regional event assignation whishes'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='preferred_language',
            field=prologin.models.CodingLanguageField(blank=True, choices=[('ada', 'Ada'), ('brainfuck', 'Brainfuck'), ('c', 'C'), ('csharp', 'C#'), ('cpp', 'C++'), ('fsharp', 'F#'), ('haskell', 'Haskell'), ('java', 'Java'), ('js', 'Javascript'), ('lua', 'Lua'), ('ocaml', 'OCaml'), ('pascal', 'Pascal'), ('perl', 'Perl'), ('php', 'PHP'), ('pseudocode', 'Pseudocode'), ('python2', 'Python 2'), ('python3', 'Python 3'), ('scheme', 'Scheme'), ('vb', 'Visual Basic')], db_index=True, help_text='The programming language you will most likely use during the regional events.', max_length=64, null=True, verbose_name='Coding language'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='shirt_size',
            field=prologin.models.EnumField(contest.models.ShirtSize, blank=True, choices=[(0, 'XS'), (1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, 'XXL')], db_index=True, help_text='We usually provide unisex Prologin t-shirts to the finalists.', null=True, verbose_name='T-shirt size'),
        ),
        migrations.AlterField(
            model_name='contestantcorrection',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contestant_correction', to=settings.AUTH_USER_MODEL),
        ),
    ]
