# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_preferred_language_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='is_home_public',
            field=models.BooleanField(default=False),
        ),
    ]
