# Generated by Django 2.1.2 on 2018-10-30 22:57

import contest.models
from django.db import migrations
import prologin.models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_contestant_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='learn_about_contest',
            field=prologin.models.EnumField(contest.models.LearnAboutContest, blank=True, choices=[(0, 'Another programming contest'), (1, 'From social media'), (2, 'From the poster in my school/university'), (3, 'From a friend'), (4, 'From an article on a website or a newspaper'), (5, 'Some other way'), (6, "I don't remember")], db_index=True, null=True, verbose_name='How did you learn about the contest ?'),
        ),
    ]
