# Generated by Django 2.1.7 on 2019-02-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='for_gcc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='center',
            name='for_prologin',
            field=models.BooleanField(default=True),
        ),
    ]
