# Generated by Django 2.2.10 on 2020-04-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qcm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_optional',
            field=models.BooleanField(default=False),
        ),
    ]
