# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 21:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('radius_meters', models.FloatField()),
                ('enable_on', models.DateTimeField()),
                ('event', models.OneToOneField(on_delete=models.CASCADE, related_name='marauder_settings', to='contest.Event')),
            ],
        ),
        migrations.CreateModel(
            name='TaskForce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('redundancy', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=models.CASCADE, related_name='task_forces', to='contest.Event')),
                ('members', models.ManyToManyField(related_name='task_forces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task force',
                'ordering': ('-event', '-redundancy', 'name'),
                'verbose_name_plural': 'Task forces',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_timestamp', models.DateTimeField(auto_now=True)),
                ('in_area', models.BooleanField(default=False)),
                ('lat', models.FloatField(default=0.0)),
                ('lon', models.FloatField(default=0.0)),
                ('gcm_app_id', models.CharField(max_length=64)),
                ('gcm_token', models.CharField(max_length=256)),
                ('user', models.OneToOneField(on_delete=models.CASCADE, related_name='marauder_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User profile',
                'ordering': ('user',),
                'verbose_name_plural': 'User profiles',
            },
        ),
        migrations.AlterUniqueTogether(
            name='taskforce',
            unique_together={('event', 'name')},
        ),
        migrations.AlterModelOptions(
            name='eventsettings',
            options={'ordering': ('event',), 'verbose_name': 'Event settings', 'verbose_name_plural': 'Events settings'},
        ),
    ]
