# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marauder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='location_timestamp',
            new_name='last_report_timestamp',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_within_timestamp',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
