# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marauder', '0002_add_within_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskforce',
            options={'ordering': ('-event', '-redundancy', '-importance', 'name'), 'verbose_name': 'Task force', 'verbose_name_plural': 'Task forces'},
        ),
        migrations.AddField(
            model_name='taskforce',
            name='importance',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
