# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marauder', '0003_add_importance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskforce',
            options={'ordering': ('-event', '-importance', '-redundancy', 'name'), 'verbose_name': 'Task force', 'verbose_name_plural': 'Task forces'},
        ),
    ]
