# Generated by Django 2.2.8 on 2019-12-12 16:05

from django.db import migrations
import prologin.models
import sponsor.models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0003_remove_order_and_editions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='rank_code',
            field=prologin.models.TextEnumField(sponsor.models.Rank, choices=[('gold', 'Gold'), ('silver', 'Silver'), ('copper', 'Copper')], db_index=True, default=2, max_length=64, verbose_name='Rank'),
            preserve_default=False,
        ),
    ]
