# Generated by Django 2.1.7 on 2019-02-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0003_remove_order_and_editions'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='for_gcc',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='for_prologin',
            field=models.BooleanField(default=True),
        ),
    ]
