#!/usr/bin/env python

from pathlib import Path
import io
import json
import os
import requests
import shutil
import sys
import tempfile
import zipfile

EMOJIONE_ZIP_URL = 'http://emojione.com/wp-content/uploads/assets/e1-png.zip'
EMOJIONE_JSON = 'https://raw.githubusercontent.com/Ranks/emojione/master/emoji.json'


def extract(zipball, member, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with zipball.open(member) as source, open(path, 'wb') as target:
        shutil.copyfileobj(source, target)


if __name__ == '__main__':
    EMOJIS_DIR = Path(sys.argv[1])
    assert "emojis" in EMOJIS_DIR.parts  # small safeguard
    EMOJI_PY_DB = Path(sys.argv[2])
    assert EMOJI_PY_DB.suffix == '.py'

    # Remove old emojis
    print("Removing old tree at", EMOJIS_DIR)
    shutil.rmtree(str(EMOJIS_DIR), ignore_errors=True)
    EMOJIS_DIR.mkdir(parents=True, exist_ok=False)

    # Get emojione tarball
    print("Downloading emojione tarball", EMOJIONE_ZIP_URL)
    # zipball = io.BytesIO(requests.get(EMOJIONE_ZIP_URL).content)
    zipball = open('/tmp/e1-png.zip', 'rb')
    print("Extracting")
    with zipfile.ZipFile(zipball) as zipball:
        for member in zipball.namelist():
            p = Path(member)
            if p.parent == Path('e1-png/png_64') and p.suffix == '.png':
                dest = EMOJIS_DIR / p.name
                print(dest)
                with zipball.open(member) as source, dest.open('wb') as target:
                    shutil.copyfileobj(source, target)

    # Build db
    emoji_db = requests.get(EMOJIONE_JSON).json()
    emoji_db = {
        key: {'unicode': value['unicode'], 'name': value['name']}
        for key, value in emoji_db.items()
    }

    # Add prologin logo small cube as :prologin: (easter-egg)
    emoji_db['prologin'] = {'unicode': 'prologin', 'name': 'Prologin'}

    # Generate .py for markdown
    print("Writing database at", str(EMOJI_PY_DB))
    with EMOJI_PY_DB.open('w', encoding='utf-8') as f:
        f.write("# THIS FILE IS GENERATED BY assets/update-emojis.py\n")
        f.write("# DO NOT EDIT\n")
        f.write("EMOJIS = ")
        f.write(repr(emoji_db))
        f.write("\n")

    print("Imported {} emojis".format(len(emoji_db)))
