#!/usr/bin/env python

from update_utils import *
import json
import io
import os
import requests
import shutil
import tempfile
import zipfile

EMOJIONE_ZIP_URL = 'http://emojione.com/wp-content/uploads/assets/e1-png.zip'
EMOJIONE_JSON = 'https://raw.githubusercontent.com/Ranks/emojione/master/emoji.json'

DESTINATION = os.path.abspath('img/emojis')

if __name__ == '__main__':
    # Remove old emojis
    print("Removing old tree at", DESTINATION)
    shutil.rmtree(DESTINATION, ignore_errors=True)
    # Get emojione tarball
    zipball = io.BytesIO(requests.get(EMOJIONE_ZIP_URL).content)
    with zipfile.ZipFile(zipball) as zipball:
        for member in zipball.namelist():
            if not member.startswith('png/64x64/') or not member.endswith('.png'):
                continue
            path = os.path.join(DESTINATION, strip_components(member, 2))
            extract_from_zip(zipball, member, path)

    emoji_db = requests.get(EMOJIONE_JSON).json()
    emoji_db = {
        key: {'unicode': value['unicode'], 'name': value['name']}
        for key, value in emoji_db.items()
    }

    # Little easter-egg
    shutil.copy2('img/prologin_emoji.png', 'img/emojis/prologin.png')
    emoji_db['prologin'] = {'unicode': 'prologin', 'name': 'Prologin'}

    # Emoji list for Markdown parsing
    with open('../utils/markdown/emoji_list.py', 'w') as f:
        f.write("# THIS FILE IS GENERATED BY update-emojis.py\n")
        f.write("# DO NOT EDIT\n")
        f.write("EMOJIS = ")
        f.write(repr(emoji_db))
        f.write("\n")

    print("Imported {} emojis".format(len(emoji_db)))
