# Generated by Django 2.2.19 on 2021-02-26 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import forum.models
import prologin.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_readstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='readstate',
            name='status',
            field=prologin.models.EnumField(forum.models.ReadState.SubscribeType, choices=[(0, 'Nothing'), (1, 'Notification'), (2, 'Mail')], db_index=True, default=0, verbose_name='Subscribe type'),
        ),
        migrations.CreateModel(
            name='NotificationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_list', to='forum.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_post_count', models.PositiveIntegerField(blank=True, default=0, editable=False, verbose_name='Number of posts')),
                ('last_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
                ('last_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='forum.Post')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='forum.Thread')),
            ],
        ),
    ]
