# Generated by Django 2.2.19 on 2021-02-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_readstate'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['title', 'forum'], name='forum_threa_title_f5950b_idx'),
        ),
    ]
