# Generated by Django 2.2.19 on 2021-02-26 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210226_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readstate',
            old_name='status',
            new_name='subtype',
        ),
    ]
