# Generated by Django 2.2.19 on 2021-02-26 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210226_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='thread',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='forum.NotificationList'),
        ),
    ]
