# Generated by Django 2.2.19 on 2021-02-27 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20210227_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='readstate',
            name='notification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='forum.Notification'),
        ),
    ]
