# Generated by Django 2.0.7 on 2018-07-15 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gcc.models
import prologin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_start', models.DateField(auto_now_add=True)),
                ('event_end', models.DateField(auto_now_add=True)),
                ('signup_start', models.DateField(auto_now_add=True)),
                ('signup_end', models.DateField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centers.Center')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcc.Edition')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('form', prologin.models.EnumField(gcc.models.Forms, choices=[(0, 'Application'), (1, 'Profile')])),
                ('response_type', prologin.models.EnumField(gcc.models.AnswerTypes, choices=[(0, 'Boolean'), (1, 'Integer'), (2, 'Date'), (3, 'String'), (4, 'Text')])),
                ('required', models.BooleanField(default=False)),
                ('meta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcc.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_applications', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('events', models.ManyToManyField(to='gcc.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcc.Event'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together={('user', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('user', 'event')},
        ),
    ]
