# Generated by Django 2.1.7 on 2019-02-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_unicode_username_django10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prologinuser',
            name='allow_mailing',
            field=models.BooleanField(blank=True, db_index=True, default=True, help_text='We only mail you to provide useful information during the various stages of the contest. We hate spam as much as you do!', verbose_name='Allow Prologin to send me emails'),
        ),
        migrations.AlterField(
            model_name='prologinuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
