# Generated by Django 2.2.17 on 2021-01-19 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_contestant_learn_about_contest'),
        ('auth', '0011_update_proxy_permissions'),
        ('oidc_provider', '0026_client_multiple_response_types'),
        ('users', '0006_authtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenIDClientPolicy',
            fields=[
                ('openid_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='oidc_provider.Client')),
                ('allow_staff', models.BooleanField(default=False, help_text='Allow staff users to login through this client.')),
                ('allow_assigned_semifinal', models.BooleanField(default=False, help_text='Allow contestants of the current edition assigned to semifinal to login through this client.')),
                ('allow_assigned_final', models.BooleanField(default=False, help_text='Allow contestants of the current edition assigned to final to login through this client.')),
                ('allow_assigned_semifinal_event', models.ForeignKey(blank=True, help_text='Allow contestants of the current edition assigned to the selected semifinal event to login through this client.', limit_choices_to={'edition': 2021, 'type': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.Event')),
                ('allow_groups', models.ManyToManyField(blank=True, help_text='If not blank, represents the groups allowed to login through this client.', to='auth.Group')),
            ],
            options={
                'verbose_name': 'OpenID Client Policy',
                'verbose_name_plural': 'OpenID Client Policies',
            },
        ),
    ]
