# Generated by Django 2.2.17 on 2021-02-11 21:55

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_openidclientpolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prologinuser',
            name='birthday',
            field=models.DateField(blank=True, null=True, validators=[users.models.validate_birthday], verbose_name='Birth day'),
        ),
    ]
